name: Renovate
on:
  schedule:
    - cron: '0 */12 * * *'  # every 6 hours
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      RENOVATE_AUTODISCOVER: true 
      RENOVATE_PLATFORM: github
      RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Renovate
        uses: renovatebot/github-action@v44.0.0
